### ISSUE TITLE
网站都可以访问了，为什么Cydia提示找不到源

### ISSUE THREAD

**Issue by Tro0t** [82Flex/DCRM#1]
![2](https://user-images.githubusercontent.com/33115695/32040337-0a7913a8-ba63-11e7-8343-8488ec4689c0.png)

访问网站是完全没问题了。但是在cydia中就找不到源。

**Comment by 0xJacky** [comment]
请尝试开启 rq-worker
```
cd /wwwdata/DCRM
nohup ./manage.py rqworker high > /dev/null &
nohup ./manage.py rqworker default > /dev/null &
```

**Comment by Tro0t** [comment]
![1](https://user-images.githubusercontent.com/33115695/32152312-4b4ad5da-bd5e-11e7-9f1c-6a9f2d5bdd6f.png)

是开启状态额。。。

**Comment by 0xJacky** [comment]
看错误信息应该是没有配置 GnuPG

请参考 GnuPG 配置示例
`apt-get install gnupg2`
Make sure to launch background queue with the same nginx working user (www/www-data).

```
su www-data
gpg --gen-key
```

**Comment by AsTryE** [comment]
我这也是找不到源，提示，网站山上面都显示正常了。后台也能登录上传deb包。就是手机Cydia上面提示找不到源地址。
