### ISSUE TITLE
Notice bug

### ISSUE THREAD

**Issue by LonestarX91** [82Flex/DCRM#10]
The notice section is bugged. When you enter a notice, if you save it and delete it (clear it) afterwards, the notice will be gone but the notice section will stay (empty). I checked the db and for some reason even if you empty the notice text view, the db saves an empty paragraph (`<p></br></p>`) which in turn makes the section show up even if it appears empty since the paragraph mentioned above doesn't actually have any text. A temporary solution and hacky work around is to manually delete the column entry for your site's preferences record from the db. If you do that and never touch the settings again it will work but if you try and change any other setting again, it will show up again

**Comment by Lessica** [comment]
We use an inline rich text editor for multi line fields, just click "HTML" button and clear that field.
