### ISSUE TITLE
Comment bug

### ISSUE THREAD

**Issue by LonestarX91** [82Flex/DCRM#12]
Upon trying to comment (from cydia nothing happens) from web getting the following error attached screenshot
<img width="504" alt="screenshot 2018-06-10 at 03 34 55" src="https://user-images.githubusercontent.com/8129596/41197242-66efc420-6c5f-11e8-8464-72af0db0b586.png">

**Comment by LonestarX91** [comment]
disabling comment module and re-enabling seemd to have solved the problem for the moment..

**Comment by LonestarX91** [comment]
can you perhaps make mail optional for comment? nobody wants to show their mail to anyone who can see the tweak

**Comment by Lessica** [comment]
Sorry I'm busy these days. These bugs have been marked and will be resolved in next major release. Thank you :-)

Zheng

**Comment by Lessica** [comment]
Fixed in 9edc5fc0be3776ca76a33583cd4e2e08891a3ebe
