### ISSUE TITLE
CalledProcessError 报了这个错请问怎么处理谢谢。

### ISSUE THREAD

**Issue by liujun001** [82Flex/DCRM#13]
Request Method: | POST
-- | --
https://127.0.0.1/admin/WEIPDCRM/build/add/
1.10.5
CalledProcessError
Command '[u'gpg', u'-abs', u'--batch', u'--yes', u'-o', u'/wwwdata/DCRM/temp/92a17c5c-02bd-4364-859e-2974e7290f25/Release.gpg', u'/wwwdata/DCRM/temp/92a17c5c-02bd-4364-859e-2974e7290f25/Release']' returned non-zero exit status 2
/usr/lib/python2.7/subprocess.py in check_call, line 541
/usr/local/bin/uwsgi
2.7.12
['.',  '',  '/usr/local/lib/python2.7/dist-packages/cloud_init-0.7.6-py2.7.egg',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']

**Comment by 0xJacky** [comment]
请参考 gpg 配置
CONFIGURE GnuPG (only if GnuPG is enabled) 配置示例

```
apt-get install gnupg2
# Make sure to launch background queue with the same nginx working user (www/www-data).

su www-data
gpg --gen-key
# or
gpg --allow-secret-key-import --import private.key
```
或者在 `WEIPDCRM -> 设置` 中关闭 `启用 GPG 签名`
