### ISSUE TITLE
无法上传10MB的包

### ISSUE THREAD

**Issue by Heyheyhaha** [82Flex/DCRM#15]
貌似不是编码问题，小一点的包是可以正常上传的。。。

https://imgchr.com/i/PuRVFf

**Comment by anserme** [comment]
nginx的问题吧

**Comment by 0xJacky** [comment]
您好，请问您是否已检查过 Nginx 的上传限制？

**Comment by Lessica** [comment]
Use Python 3.7 and try latest version.
