### ISSUE TITLE
nginx: [emerg] "upstream" directive is not allowed here in /etc/nginx/nginx.conf:1

### ISSUE THREAD

**Issue by daren1992** [82Flex/DCRM#16]
您好，博主，当我把 NGINX 配置修改好域名后放在 /etc/nginx/nginx.conf
执行 nginx -t
 出现nginx: [emerg] "upstream" directive is not allowed here in /etc/nginx/nginx.conf:1
（原来的里面的代码给我清空了）
请问怎么解决？

**Comment by 0xJacky** [comment]
请贴出 nginx.conf 的内容
