### ISSUE TITLE
考虑出个docker版吗？

### ISSUE THREAD

**Issue by sephilex** [82Flex/DCRM#23]
看到issue很多问题都是安装配置的问题，可以考虑用docker，暴露出端口和配置文件就可以了

**Comment by jjss520** [comment]
支持，支持，docker版的多方便呀

**Comment by Lessica** [comment]
不是专业后端，这两天试试……谢谢建议

发自我的 iPhone

**Comment by jjss520** [comment]
> ……谢谢建议

期待

**Comment by jjss520** [comment]
一直等着，没动静呀

**Comment by Lessica** [comment]
@jjss520 现已支持 Docker 快速部署
