### ISSUE TITLE
is a directory

### ISSUE THREAD

**Issue by yordon96** [82Flex/DCRM#25]
最后一步build提示目录是一个文件夹，不知道是哪个命令出错了
IOError at /admin/WEIPDCRM/build/add/
[Errno 21] Is a directory: u'/www/wwwroot/DCRM/resources/'
Request Method:	POST
Request URL:	http://jp.yordon.ml/admin/WEIPDCRM/build/add/
Django Version:	1.10.5
Exception Type:	IOError
Exception Value:	
[Errno 21] Is a directory: u'/www/wwwroot/DCRM/resources/'
Exception Location:	/usr/lib/python2.7/shutil.py in copyfile, line 82
Python Executable:	/usr/local/bin/uwsgi
Python Version:	2.7.12
Python Path:	
['.',
 '',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat']

**Comment by Lessica** [comment]
Fixed in commit 70986ff5e116245b784ae2b85c068d8c9d40d33c
