### ISSUE TITLE
后台Photologue-Galleries-添加 gallery报错

### ISSUE THREAD

**Issue by pone** [82Flex/DCRM#28]
点击添加 gallery报错（ build_attrs() got an unexpected keyword argument 'name' ）
原因为sortedm2m不兼容django 1.11
目前sortedm2m作者已经解决更新。用作者sortedm2m-1.5.0版本替换sortedm2m文件。bug fix

**Comment by Lessica** [comment]
Fixed in 3c38871647c36a80adce40e997a24fa9eb4c4334
