### ISSUE TITLE
我在群晖上搭建DCRM，遇到点问题

### ISSUE THREAD

**Issue by jjss520** [82Flex/DCRM#31]
直接跑的docker-compose.yml，前面各种错误，各种百度后命令成功跑完，但打开ip:端口，出现

Request Method: | GET
-- | --
http://10.10.10.10:8888/index/
1.11.23
ProgrammingError
(1146, "Table 'DCRM.django_site' doesn't exist")
/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py in query, line 224
/usr/local/bin/uwsgi
3.7.5
['.',  '',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Sat, 30 Nov 2019 13:33:20 +0800

应该是数据库没对，不知道怎么解决，我是直接跑的第二条命令，第一条git clone --depth 1 https://github.com/82Flex/DCRM.git &&  cd DCRM
-ash: git: command not found
应该是没安装git
能帮忙解决一下吗

**Comment by Lessica** [comment]
你如果查点资料不用 Google 而是用百度的话，无论什么问题你都解决不了。你下载源代码 zip 的方式而用 git 克隆仓库方式获得源代码，可以无需第一步；只是之后更新 DCRM 会比较麻烦。

注：Docker 的部署和使用不在讨论范围之内。

你需要使用目前主分支上最新的代码：试着使用命令 4 登入容器 `dcrm_app_1`，在该容器中执行 `python manage.py migrate` 看一下数据库迁移有没有什么问题。

**Comment by jjss520** [comment]
装好了，谢谢
