### ISSUE TITLE
NoReverseMatch at /index/

### ISSUE THREAD

**Issue by ducbo** [82Flex/DCRM#38]
I upload 500 packages

**Debug log**
`

Exception Type: | NoReverseMatch
-- | --
Reverse for 'index_page' with arguments '(28,)' not found. 1 pattern(s) tried: ['index/(?P<page>\\d?)/?$']
/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/usr/local/bin/uwsgi

`

**Comment by Lessica** [comment]
Fixed in https://github.com/82Flex/DCRM/commit/f43e2a453ad713e225addd557b249676afb8cb0d
