### ISSUE TITLE
能把dcrm打包成一个docker镜像吗

### ISSUE THREAD

**Issue by jjss520** [82Flex/DCRM#39]
用群晖搭建，出来好几个容器，能打包成一个吗？这样还方便操作

**Comment by Lessica** [comment]
Docker 能的话就应该能吧，应该还能做数据迁移

**Comment by jjss520** [comment]
> Docker 能的话就应该能吧，应该还能做数据迁移

能打包一下吗

**Comment by Lessica** [comment]
你自己按你的需求打包，不是专门做给你群晖用的……
