### ISSUE TITLE
ERROR: Service 'scheduler' failed to build

### ISSUE THREAD

**Issue by talting** [82Flex/DCRM#42]
ERROR: Service 'scheduler' failed to build: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/e56ee33998f867cad60403fbd8e0b50d6d19302711e63adb82a7fd1071556fda\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
怎么办？

**Comment by Lessica** [comment]
目测没用 `sudo`……

**Comment by talting** [comment]
好吧确实没用
