### ISSUE TITLE
请问下这个ERROR是什么造成的，mac电脑和服务器都这个错误

### ISSUE THREAD

**Issue by ghost** [82Flex/DCRM#43]
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t97hq5n_/python-akismet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t97hq5n_/python-akismet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8z2_x4_a
         cwd: /tmp/pip-install-t97hq5n_/python-akismet/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-t97hq5n_/python-akismet/setup.py", line 186, in <module>
        install_requires = [str(ir.req) for ir in requirements]
      File "/tmp/pip-install-t97hq5n_/python-akismet/setup.py", line 186, in <listcomp>
        install_requires = [str(ir.req) for ir in requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Lessica** [comment]
Google 了一下发现第三方依赖 `python-akismet` 的 `0.4.1` 版本存在问题，其作者已于2天前在 `0.4.2` 版本修复：https://github.com/Nekmo/python-akismet/commit/3f52bd2ab9f285311453d1fa4d53081d69573ad5

**Comment by Lessica** [comment]
已修复：
https://github.com/82Flex/DCRM/blob/1da3a823966eb9ae189490f041f03e2f759c0967/requirements.txt#L28
