### ISSUE TITLE
无法找到APT 软件源

### ISSUE THREAD

**Issue by ghost** [82Flex/DCRM#47]
按照步骤完成docker源搭建之后,能打开源网页,再添加的时候就显示 无法找到APT 软件源

**Comment by Lessica** [comment]
添加元数据和发布流程：https://github.com/82Flex/DCRM#4-publish-repository-%E5%8F%91%E5%B8%83%E8%BD%AF%E4%BB%B6%E6%BA%90

**Comment by ghost** [comment]
按照你YouTube上的流程已经操作过了 地址是 repo.jiuyi.fun 就是添加不了

**Comment by Lessica** [comment]
域名没解析
