### ISSUE TITLE
构建并启动 DCRM 容器 Step 4 ERROR

### ISSUE THREAD

**Issue by Sakuracio** [82Flex/DCRM#48]
docker-compose up --build --detach
第4步时报错 请问什么原因
ERROR: Service 'scheduler' failed to build: oci runtime error: container_linux.go:235: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""

**Comment by dr03m** [comment]
Getting same error, has this been solved?
Google Translate/谷歌翻译:
遇到同样的错误，这个问题解决了吗？

**Comment by disonwei** [comment]
同问 ERROR: Service 'scheduler' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
