### ISSUE TITLE
目前bug还是比较多的，希望能够不断的完善

### ISSUE THREAD

**Issue by wuweida** [82Flex/DCRM#5]
废了一番周折centos7而且不熟悉Python环境，搭建起来了，看了下bug太多了，选项各方面还是比较少。
对我而言我更喜欢php版（### 毕竟是世界上最好的语言）哈哈哈，希望早日出正式版

**Comment by Lessica** [comment]
还好吧，一直有在维护，有 Bug 可以提出来。
主要是配置有些麻烦，毕竟软件源的特性摆在这。

如果做了一键部署，就很难适应各种情况，所以要让你把整个都自己配置一遍，熟悉它的情况。因为你不配 OSS/CDN 支持的话，流量和带宽都是很难办的。哪怕你用 php 来搭也是要经历这个过程会比较好一些。
