### ISSUE TITLE
ERROR: for dcrm_worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-

### ISSUE THREAD

**Issue by aadog** [82Flex/DCRM#57]
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Creating dcrm_memcached ... done
Creating dcrm_db        ... done
Creating dcrm_redis     ... done
WARNING: The "worker-high" service is using the custom container name "dcrm_worker-high". Docker requires each container to have a unique name. Remove the custom name to scale the service.
Creating dcrm_scheduler      ... done
Creating dcrm_worker-default ...
Creating dcrm_app            ... done
Creating dcrm_worker-high    ... error
Creating dcrm_worker-high    ...
Creating dcrm_worker-default ... done

ERROR: for dcrm_worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-high" is already in use by container "1891f8eed617976cbe6e37e2ef3b7f41c6cf3564b755e5089f9fc1f9f4d2804d". You have to reCreating dcrm_pure-ftpd      ... done

ERROR: for worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-high" is already in use by container "1891f8eed617976cbe6e37e2ef3b7f41c6cf3564b755e5089f9fc1f9f4d2804d". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

**Comment by Lessica** [comment]
不负责解决 Docker 使用方面的问题

**Comment by qq2519157** [comment]
将docker-compose.yml中101行replicas的值由 2 改为 1
