### ISSUE TITLE
后台队列进程无法启动

### ISSUE THREAD

**Issue by RudyQin** [82Flex/DCRM#6]
根据手册安装到最后执行
nohup ./manage.py rqworker high > /dev/null &
nohup ./manage.py rqworker default > /dev/null &
无法执行，我查看了一下manage.py没有rqworker这个启动参数，是文档问题吗？还是安装不对。

**Comment by wuweida** [comment]
这个是www用户的运行结果
bash-4.2$ nohup: ignoring input and redirecting stderr to stdout
nohup: ignoring input and redirecting stderr to stdout

[1]-  Exit 1                  nohup ./manage.py rqworker high > /dev/null
[2]+  Exit 1                  nohup ./manage.py rqworker default > /dev/null

下面是root用户的运行结果
# nohup ./manage.py rqworker high > /dev/null & nohup ./manage.py rqworker default > /dev/null &
[1] 24436
[2] 24437
# nohup: ignoring input and redirecting stderr to stdout
nohup: ignoring input and redirecting stderr to stdout


我不清楚这是哪个地方导致的问题，我用的是centos 7.4，我Google了一下也用用户会出现nohup: ignoring input and redirecting stderr to stdout
这个问题。会不会是配置问题导致的呢？
昨天我也和Jacky讨论了一下，我发现好多处bug等下我整理一下发给你吧！

**Comment by 0xJacky** [comment]
> nohup: ignoring input and redirecting stderr to stdout
> nohup: ignoring input and redirecting stderr to stdout

是系统输出的，出现这个结果证明已经开启成功了，建议还是先去了解下 nohup 的用法。

**Comment by RudyQin** [comment]
不是的，我用./manage.py help查询参数，没有rqworker
./manage.py help
Django Redis Queue: Disabled
Django Cache: Disabled

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

[threadedcomments]
    migrate_comments
    migrate_threaded_comments

**Comment by 0xJacky** [comment]
打开 DCRM/settings.py 
找到 ENABLE_REDIS = False
将 False 改成 True

**Comment by RudyQin** [comment]
真就是没开启redis的问题。。。谢谢了！！！
现在有个问题，我进后台编辑sites，然后增加了自己的站点，把example.com删除了，结果直接奔溃了。。。

Request Method: | GET
-- | --
https://apt.xxx.net/index/
1.10.5
DoesNotExist
Site matching query does not exist.
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 385
/usr/local/bin/uwsgi
2.7.12
['.',  '',  '/usr/local/lib/python2.7/dist-packages/cloud_init-0.7.6-py2.7.egg',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Sun, 14 Jan 2018 13:11:08 +0800

只能重新安装了吗？

**Comment by 0xJacky** [comment]
改一下 SITE_ID 试试吧

**Comment by RudyQin** [comment]
真行了。。。改django_site，把增加的site的id改为1就可以了，感谢~~
