### ISSUE TITLE
使用手动部署，但是现在不知为什么访问ip+8000无法访问

### ISSUE THREAD

**Issue by zsbai** [82Flex/DCRM#62]
<img width="490" alt="截屏2021-06-22 上午12 23 37" src="https://user-images.githubusercontent.com/62942942/122795633-1880a480-d2f0-11eb-86a8-3300915932cc.png">

**Comment by zsbai** [comment]
<img width="567" alt="截屏2021-06-22 上午12 29 11" src="https://user-images.githubusercontent.com/62942942/122796349-df94ff80-d2f0-11eb-8e1a-a0f3bae92126.png">

python3 manage.py runserver 0.0.0.0:8000 使用此指令可以成功访问

**Comment by Lessica** [comment]
Django 自带的 runserver 仅供测试时使用，不宜用于生产环境。
https://docs.djangoproject.com/en/3.2/ref/django-admin/#runserver

**Comment by zsbai** [comment]
> Django 自带的 runserver 仅供测试时使用，不宜用于生产环境。
> 
> https://docs.djangoproject.com/en/3.2/ref/django-admin/#runserver

好的，谢谢提醒

**Comment by zsbai** [comment]
> Django 自带的 runserver 仅供测试时使用，不宜用于生产环境。
> https://docs.djangoproject.com/en/3.2/ref/django-admin/#runserver

你好，再请教一个问题，我现在搭建完成后上传东西全部报错500
[pid: 441|app: 0|req: 1/3] 172.18.0.1 () {50 vars in 951 bytes} [Tue Jun 22 19:23:44 2021] POST /admin/upload/ => generated 1121 bytes in 204 msecs (HTTP/1.0 500) 4 headers in 143 bytes (1 switches on core 0)

文件很小也报错，只有49kb，检查过好像也不是nginx的配置的问题.....

开发模式日志：
[22/Jun/2021 19:34:34] "POST /admin/upload/ HTTP/1.0" 500 1121
自己看不太懂..不知是哪里错了

**Comment by zsbai** [comment]
> Django 自带的 runserver 仅供测试时使用，不宜用于生产环境。
> https://docs.djangoproject.com/en/3.2/ref/django-admin/#runserver

过了一段时间发现可以上传了，但会一直卡在“上传成功，处理中”

**Comment by zsbai** [comment]
<img width="919" alt="截屏2021-06-22 下午10 58 25" src="https://user-images.githubusercontent.com/62942942/122948297-64ddea00-d3ad-11eb-8fb1-897ca4129f4b.png">

**Comment by Lessica** [comment]
https://github.com/82Flex/DCRM#535-configure-workers

**Comment by zsbai** [comment]
> https://github.com/82Flex/DCRM#535-configure-workers

奥，不好意思当时不太清楚worker是干嘛用的就没有配置😥

**Comment by Lessica** [comment]
`ENABLE_REDIS` 关掉，不用任务队列反正也是可以的。

**Comment by Lessica** [comment]
能凑合用就凑合一下，没精力维护这个项目

**Comment by zsbai** [comment]
已经差不多搭建完成啦，万分感谢，本来是个优秀的项目，有点可惜
