### ISSUE TITLE
Error Docker

### ISSUE THREAD

**Issue by sharklatan** [82Flex/DCRM#64]
`Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
dcrm_redis is up-to-date
dcrm_db is up-to-date
dcrm_memcached is up-to-date
WARNING: The "worker-high" service is using the custom container name "dcrm_worker-high". Docker requires each container to have a unique name. Remove the custom name to scale the service.
dcrm_scheduler is up-to-date
dcrm_app is up-to-date
dcrm_worker-default is up-to-date
dcrm_pure-ftpd is up-to-date
Creating dcrm_worker-high ... error

ERROR: for dcrm_worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-high" is already in use by container "1831bd5629c0aa27c73c2e7cf9b27f0ebd406c52cb04cb0db30cad37f8d5aa9b". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-high" is already in use by container "1831bd5629c0aa27c73c2e7cf9b27f0ebd406c52cb04cb0db30cad37f8d5aa9b". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.`

**Comment by kxl2005** [comment]
WARNING: The "worker-high" service is using the custom container name "dcrm_worker-high". Docker requires each container to have a unique name. Remove the custom name to scale the service.
dcrm_app is up-to-date
dcrm_scheduler is up-to-date
dcrm_worker-default is up-to-date
dcrm_pure-ftpd is up-to-date
Creating dcrm_worker-high ... error

ERROR: for dcrm_worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-high" is already in use by container "f7b664c07ba1cdb0ba51cfec657f89de74e28a5fbd723b09a1102c86ef5ce20d". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for worker-high  Cannot create container for service worker-high: Conflict. The container name "/dcrm_worker-high" is already in use by container "f7b664c07ba1cdb0ba51cfec657f89de74e28a5fbd723b09a1102c86ef5ce20d". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

**Comment by 4kplayeee** [comment]
thats been happing to me

**Comment by 4kplayeee** [comment]
i go t it is really easy

**Comment by 4kplayeee** [comment]
I know how to fix this I. Need someone to help me with nginx pls

**Comment by 4kplayeee** [comment]
Order Your DRCM Server Here 
cheap prices
https://deck-hosting.com/index.php?_url=/order

**Comment by sharklatan** [comment]
> Order Your DRCM Server Here
> cheap prices
> **HIDE**

why rent a server when it has not yet been tested if it will work as expected, the most viable option is to use a local server or an existing one, and after that go configure and solve errors, after that I would consider ordering a server, otherwise you would be wasting time


or what do they do with a server if they can't run it or resolve errors first 🤷🏽‍♂️

in the same way they need a test server to update or  add extra features, or it will implement things on the platform and risk security, service stability 🤷🏽‍♂️

**Comment by 4kplayeee** [comment]
we fixed the issues you can see it here https://cocotweaks-servers-1.win/ no problems

**Comment by sharklatan** [comment]
> we fixed the issues you can see it here **HIDE LINK** no problems

I'm not saying it doesn't work and it can't be repaired because I did it anyway, but you're paying for a server that doesn't have anything defined yet, or what types of tweaks it uploaded, so all that unused time is an expense, then come the network tests , cdn etc.

**Comment by 4kplayeee** [comment]
They can upload whatever they want everyone is going to have there separate servers

**Comment by Hintay** [comment]
Please do not believe any advertisements. We will fix this issue in a future version.

**Comment by 4kplayeee** [comment]
Don’t say ur going to fix it now is been 3 years

**Comment by 0xJacky** [comment]
try to run `docker stop dcrm_worker-high && docker rm dcrm_worker-high` then build image again.
