### ISSUE TITLE
哪里可以修改语言

### ISSUE THREAD

**Issue by RudyQin** [82Flex/DCRM#7]
按照文档安装后可以使用，但是都是英文界面，怎么变为中文界面？

**Comment by Lessica** [comment]
仅前端页面支持中文, 后台页面目前没有进行汉化.
修改前端页面语言请在 DCRM/settings.py 中修改 LANGUAGE_CODE 为 "zh_Hans".

**Comment by wuweida** [comment]
LANGUAGE_CODE改为zh-Hans

**Comment by RudyQin** [comment]
修改后，重新启动了UWSGI，但是首页还是英文，需要怎么才能生效？

**Comment by 0xJacky** [comment]
修改为 zh-hans

**Comment by RudyQin** [comment]
![image](https://user-images.githubusercontent.com/15032178/34929231-917c15c4-f9fd-11e7-8d75-9d7b62c11c2b.png)
还是英文

**Comment by wuweida** [comment]
@RudyQin 
“-” or "_"
![snip20180115_21](https://user-images.githubusercontent.com/6135951/34930553-f2c7fa30-fa04-11e7-9db9-441bb52c3c4c.png)

**Comment by RudyQin** [comment]
可以了，感谢~~
