### ISSUE TITLE
安装“requirements”的时候提示The unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by CHNmyx** [82Flex/DCRM#70]
![图片](https://user-images.githubusercontent.com/78731550/166653787-5c33a073-4e9c-496d-97af-572b86a2c4ed.png)
这是问题的详细代码：
WARNING: Some services (worker-default, worker-high) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Building scheduler
Step 1/6 : FROM python:3.7
 ---> 7c891de3e220
Step 2/6 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 3fb08074fed9
Step 3/6 : COPY requirements.txt ./
 ---> Using cache
 ---> 3227e9743bf7
Step 4/6 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 2b3d413f8f8f
Collecting django-contrib-comments
  Cloning git://github.com/django/django-contrib-comments.git (to revision f498cee0e04a4bcd4e061b25805c83ef08e9e536) to /tmp/pip-install-x_eut7vj/django-contrib-comments_24a32224f78c4c82b10d7e3da8a03d19
  Running command git clone --filter=blob:none --quiet git://github.com/django/django-contrib-comments.git /tmp/pip-install-x_eut7vj/django-contrib-comments_24a32224f78c4c82b10d7e3da8a03d19
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/django/django-contrib-comments.git /tmp/pip-install-x_eut7vj/django-contrib-comments_24a32224f78c4c82b10d7e3da8a03d19 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/django/django-contrib-comments.git /tmp/pip-install-x_eut7vj/django-contrib-comments_24a32224f78c4c82b10d7e3da8a03d19 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

麻烦您看下，谢谢！

**Comment by 0xJacky** [comment]
尝试修改 `requirements.txt`
将所有的 `git+git://` 改为 `git+https://` 然后重新执行镜像构建命令

**Comment by CHNmyx** [comment]
> 尝试修改 `requirements.txt` 将所有的 `git+git://` 改为 `git+https://` 然后重新执行镜像构建命令

老哥  我也找到了一个解决办法，就是把这些链接上面带有注释“#”的内容前面去掉“#”，再去掉git+git://后面的链接即可

比如：
#django-threadedcomments==1.2
git+git://github.com/Lessica/django-threadedcomments.git@266100f85570701ee6134e531ee1293584680c11#egg=django-threadedcomments
变成：
django-threadedcomments==1.2
#git+git://github.com/Lessica/django-threadedcomments.git@266100f85570701ee6134e531ee1293584680c11#egg=django-threadedcomments（或者删掉）
也可以正常下载requirements的内容。

再次表达感谢，谢谢您！

**Comment by 0xJacky** [comment]
好的
