### ISSUE TITLE
class DjangoRQ(Queue): NameError: name 'Queue' is not defined

### ISSUE THREAD

**Issue by lt-fancy** [82Flex/DCRM#8]
运行./manage.py collectstatic
报如上错误

**Comment by Lessica** [comment]
如果你希望开启 Redis Queue 后台处理队列，请保持 settings.py 中 ENABLE_REDIS 为 True：

```shell
apt-get install redis-server
pip install rq
```
如果你不需要，软件包等操作会实时完成，只需要将 ENABLE_REDIS 设为 False 即可。
