### ISSUE TITLE
Twitter link

### ISSUE THREAD

**Issue by LonestarX91** [82Flex/DCRM#9]
The twitter part of the social module is not working. you can input a twitter name/link, it will show up but when you try to click it it won't take you to the twitter profile but it will just open a new window of the repo itself

**Comment by 0xJacky** [comment]
Hi, this issue should be fixed in commit [1fe0e92](https://github.com/82Flex/DCRM/commit/1fe0e921cfe868f60fcfadc8a4d72a64115ecbf3)
